# Generated by Django 4.2.23 on 2025-08-14 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/')),
                ('sender', models.CharField(max_length=100)),
                ('caption', models.CharField(max_length=500)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('hashtags', models.ManyToManyField(related_name='photos', to='memories.hashtag')),
            ],
        ),
    ]
